- hosts: 'prod'
  tasks:
    - name: Install community packages
      community.general.pacman:
        state: present
        update_cache: yes
        name:
          - freecad
          - inkscape
          - blender
          - krita
          - libreoffice-fresh
          - libreoffice-fresh-cs
          - steam
          - code
          - neovim
          - lutris
          - vlc
          - obs-studio
          - flameshot
          - obsidian
          - giggle
          - keepass
          - easyeffects
          - qbittorrent
          - gparted
          - solaar
          - lf
          - discord
          - thunderbird
      become: yes

    - name: Install AUR packages with yay
      ansible.builtin.shell:
        cmd: "yay -S --noconfirm {{ item }}"
      loop:
        - orca-slicer-bin
        - brave-bin
        - spotify
        - postman-bin
        - vesktop
        - heroic-games-launcher-bin
        - alvr
        - bottles
        - davinci-resolve
        - openrgb-bin

