- hosts: 'prod'
  tasks:
    - name: Update
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install Go (dependency for yay)
      community.general.pacman:
        name: go
        state: present
        update_cache: yes
      become: yes

    - name: Clone yay repository
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: '/tmp/yay'
      become: no

    - name: Build yay package
      ansible.builtin.shell:
        cmd: 'makepkg -s'
        chdir: '/tmp/yay'
      become: no

    - name: install yay package
      ansible.builtin.shell:
        cmd: 'sudo pacman -U yay*.pkg.tar.zst --noconfirm'
        chdir: '/tmp/yay'
      become: yes

    - name: Remove tmp files
      ansible.builtin.shell:
        cmd: |
          rm -rf /tmp/yay
      become: yes
