- hosts: 'prod'
  tasks:
    - name: UI customization
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-black' &&
        gsettings set org.gnome.desktop.interface gtk-theme "Graphite-Dark" &&
        gsettings set org.gnome.shell.extensions.user-theme name "Graphite-Dark" &&
        gnome-extensions install dash-to-panel &&
        unzip extension.zip -d ~/.local/share/gnome-shell/extensions/dash-to-panel &&
        gnome-extensions enable dash-to-panel