- hosts: 'prod'
  become: yes
  tasks:
    - name: Ensure /etc/sudoers.d exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'
      become: yes
    
    - name: Create passwordless sudo file for 'kopy'
      ansible.builtin.copy:
        dest: /etc/sudoers.d/kopy_nopasswd
        content: |
          kopy ALL=(ALL) NOPASSWD: /usr/bin/pacman
        mode: '0440'
        validate: visudo -cf %s
      become: yes
    
    - name: Allow 'kopy' passwordless sudo for specific commands
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/kopy_nopasswd
        line: 'kopy ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: '0440'
        validate: visudo -cf %s
      become: yes



