- hosts: 'prod'
  become: yes
  tasks:
    - name: Update
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install Go (dependency for yay)
      community.general.pacman:
        name: go
        state: present
        update_cache: yes
      become: yes

    - name: Clone yay repository
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: '/tmp/yay'
      become: no

    - name: Build yay package
      ansible.builtin.shell:
        cmd: 'makepkg -s'
        chdir: '/tmp/yay'
      become: no

    - name: install yay package
      ansible.builtin.shell:
        cmd: 'sudo pacman -U yay*.pkg.tar.zst --noconfirm'
        chdir: '/tmp/yay'
      become: yes

    - name: Remove tmp files
      ansible.builtin.shell:
        cmd: 'sudo rm -rf /tmp/yay'
      become: yes
    
    - name: Ensure /etc/sudoers.d exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'
      become: yes
    
    - name: Create passwordless sudo file for 'kopy'
      ansible.builtin.copy:
        dest: /etc/sudoers.d/kopy_nopasswd
        content: |
          kopy ALL=(ALL) NOPASSWD: /usr/bin/pacman
          kopy ALL=(ALL) NOPASSWD: /usr/bin/docker
        mode: '0440'
        validate: visudo -cf %s
      become: yes
    
    - name: Allow 'kopy' passwordless sudo for specific commands
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/kopy_nopasswd
        line: 'kopy ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: '0440'
        validate: visudo -cf %s
      become: yes
    
    - name: Installing pipewire and all its dependencies
      ansible.builtin.shell:
        cmd: "yay -S --noconfirm {{ item }}"
      loop:
        - pipewire
        - pipewire-pulse
        - pipewire-alsa
        - pipewire-jack
        - easyeffects
        - qjackctl
      
    - name: Installing dev kits
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - nodejs
        - code
        - docker
        - neovim
        - docker-compose
        - dotnet-sdk-7.0
        - dotnet-runtime-7.0
        - bottles
        - zsh
        - neofetch
        - postman-bin
        - giggle
        - lf
        - godot-git
        - balena-etcher
        - virtualbox
      become: yes
      become_user: kopy

    - name: Installing MM apps
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - freecad
        - davinci-resolve
        - obs-studio
        - vlc
        - inkscape
        - blender
        - krita
        - discord
        - vesktop
        - flameshot
      become: yes
      become_user: kopy
    
    - name: Installing Productive apps
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - obsidian
        - thunderbird
        - libreoffice-fresh
        - libreoffice-fresh-cs
        - orca-slicer-bin
        - spotify
        - brave-bin
      become: yes
      become_user: kopy

    - name: Installing Gamming apps
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - lutris
        - heroic-games-launcher-bin
        - alvr
        - steam
      become: yes
      become_user: kopy
    
    - name: Installing BTRFS utils
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - snapper
        - snap-pac
        - btrfs-assistant
        - snapper-support
        - grub-btrfs
        - btrfsmaintenance
        - os-prober-btrfs
      become: yes
      become_user: kopy

    - name: Installing Settings + other apps
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - solaar
        - gparted
        - qbittorrent
        - openrgb-bin
        - gnome-tweaks
        - keepass
        - file-roller
        - eog
        - gedit
        - gnome-sound-recorder
        - gnome-terminal
        - gnome-boxes
        - gnome-shell-extensions
        - pamac-aur
        - libpamac-aur
        - plex-media-player
        - plex-media-server
        - zerotier-one
        - tela-circle-icon-theme-all
        - gtk-engine-murrine
        - graphite-gtk-theme
      become: yes
      become_user: kopy
    
    - name: Install wine and all its dependencies
      ansible.builtin.shell:
        cmd: "yay -Syu --noconfirm {{ item }}"
      loop:
        - wine-nine
        - wine-installer
        - winetricks
        - vkd3d
        - wine-gecko
        - wine-mono
        - wine
      become: yes
      become_user: kopy

    - name: Enable zerotier
      ansible.builtin.shell: |
        systemctl enable zerotier-one.service
        systemctl start zerotier-one.service
      become: yes

    - name: Enable docker
      ansible.builtin.shell: |
        systemctl enable docker.service
        systemctl start docker.service
      become: yes

    - name: Setting fish as main shell
      ansible.builtin.shell:
        cmd: 'sudo usermod -s /usr/bin/zsh kopy'
      become: yes

    - name: Deploying portainer
      ansible.builtin.shell: |
         docker volume create portainer_data &&
         docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

    - name: Enable user theme
      ansible.builtin.shell: |
        gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com
        
    - name: UI customization
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-black' &&
        gsettings set org.gnome.desktop.interface gtk-theme "Graphite-Dark" &&
        gsettings set org.gnome.shell.extensions.user-theme name "Graphite-Dark" &&
        gnome-extensions install 1160 &&
        gnome-extensions enable 1160


