- hosts: 'prod'
  tasks:
    - name: Install AUR packages with yay
      ansible.builtin.shell:
        cmd: "yay -S --noconfirm {{ item }}"
      loop:
          - pipewire
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
          - qjackctl
